# Generated by Django 6.0.6 on 2026-06-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_note_title_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Employee', max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('note', 'user'), name='unique_note_membership')],
            },
        ),
    ]
