"""
Django settings for boilerplate project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from repo-root .env (gitignored).
load_dotenv(BASE_DIR.parent / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str, default: str = '') -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# HTTP Strict Transport Security (HSTS) tells always use HTTPS, never use HTTP
if env_bool('HSTS', False):
    SECURE_HSTS_SECONDS = 31536000
# Until nex year BROWSER itself uses HTTPS, after 1 year it may access using HTTP, if that time HSTS is turned off, if still turned on, another HSTS header is sent as cookie
# Increase the time as the stability of TLS certificate is confirmed
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# Tells browsers to include this site in their HSTS preload list, ensuring HTTPS is enforced even on the first visit.
# For rollback reasons suppose, TLS expires for domain (HTTPS fails) then HTTP access is not allowed on the browser, due to preload.
# TURN ON after maturity of the site and TLS certificate stability is confirmed.

# DEV SERVER DOES NOT ALLOW SSL/TSL
SECURE_SSL_REDIRECT = env_bool('SSL', False)
CSRF_COOKIE_SECURE = env_bool('SSL', False)
SESSION_COOKIE_SECURE = env_bool('SSL', False)
if env_bool('X_FORWARD',True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO","https",)
# This tells Django: "If Nginx hands you an X-Forwarded-Proto header that says 'https', treat the request as fully secure."

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'LONG_RANDOM_STRING',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '3600'))
# SESSIONS END WHEN AGE EXPIRES
SESSION_EXPIRE_AT_BROWSER_CLOSE = env_bool('SESSION_EXPIRE_AT_BROWSER_CLOSE', False)

# Public URLs consumed by the frontend config endpoint and OpenAPI.
API_BASE_URL = os.getenv('API_BASE_URL', '').rstrip('/')
SITE_BASE_URL = os.getenv('SITE_BASE_URL', 'http://localhost:8000').rstrip('/')
ADMIN_URL = os.getenv('ADMIN_URL', '/admin/')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # for legacy systems? May or may not be needed. Now http is processed (frontend) in clientside, so sessions are not as necessary. But they are still used for the admin site and other features.
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'learning.apps.LearningConfig',
    "debug_toolbar", # useful for viewing sequel queries through the 'view', requests and response
    'schema_viewer',
    # 'drf_spectacular',
]
# The migrate command looks at the INSTALLED_APPS setting
# and creates any necessary database tables according to the database settings in your boilerplate/settings.py file
# and the database migrations shipped with the app.

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Every HTTP/1.1 request requires a Host header telling the server which site you are trying to reach.
# If web applications blindly trust this input to generate dynamic links, they become vulnerable.
# Clients are redirect (302/1) to forbidden endpoint, resulting in Cache poisoning, password exposure, etc
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,.localhost,[::1]')
# White lists
# Can be done in deployement server also

if env_bool('X_FORWARD',True):
    USE_X_FORWARDED_HOST = True
# This tells Django: "If Nginx hands you an X-Forwarded-Host header treat that as your host header"
# Problem:  If Nginx routes traffic internally to localhost, Django might mistakenly try to generate links or execute CSRF validation checks against localhost instead of yourdomain.com.

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

ROOT_URLCONF = 'boilerplate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boilerplate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'my_django_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'pass'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================================
# CHUNK 1: AUTHENTICATION BACKENDS
# ============================================================================
# Configure custom authentication backends for email-based and token-based auth.
# Django queries these in order; first match wins.
# Flow: authenticate() -> backend.authenticate() -> backend.get_user().

# CHOOSE YOUR HASHING LOGIC, IN ORDER OF PRECEDENCE
# STORED AS <algorithm>$<iterations>$<salt/seed>$<hash>
# OTHER LOGICS ENABLES, CHECKING OF PASSWORDS WITH THAT HASHING LOGIC, BUT NEW PASSWORDS WILL BE HASHED WITH THE FIRST LOGIC IN THE LIST.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/
AUTHENTICATION_BACKENDS = [
    # Allow login via email and password (instead of default username).
    'learning.auth_backends.SimpleEmailBackend',
    # Allow login via bearer token (API keys, JWT, etc.).
    'learning.auth_backends.TokenBackend',
    # Fall back to default username/password auth if custom backends fail.
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Specifies where to collect from, if files are in <project>/<app_name>/static, no need
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
#     ('frontend', os.path.join(BASE_DIR.parent, 'frontend')),
# ]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    # The developer's IP address to access the debug toolbar
    os.getenv('DEV_IP',"127.0.0.1",),
]

# # Third-party gateway settings (demo defaults; override via env vars).
# THIRD_PARTY_BASE_URL = os.getenv("THIRD_PARTY_BASE_URL", "http://localhost:9000")
# THIRD_PARTY_USER = os.getenv("THIRD_PARTY_USER", "demo")
# THIRD_PARTY_PASSWORD = os.getenv("THIRD_PARTY_PASSWORD", "demo")
# THIRD_PARTY_TIMEOUT_SECONDS = int(os.getenv("THIRD_PARTY_TIMEOUT_SECONDS", "3"))
#
# # Idempotency cache windows (seconds) for transactional requests.
# TRANSACTION_PENDING_TTL_SECONDS = int(os.getenv("TRANSACTION_PENDING_TTL_SECONDS", "300"))
# TRANSACTION_COMPLETED_TTL_SECONDS = int(os.getenv("TRANSACTION_COMPLETED_TTL_SECONDS", "900"))
# TRANSACTION_REVERSE_AFTER_SECONDS = int(os.getenv("TRANSACTION_REVERSE_AFTER_SECONDS", "600"))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}