"""
Django settings for boilerplate project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y+(enu1o@2zv6t6b1n#p+02(08_8pd4*b29l##g+nrp6oijj=2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # for legacy systems? May or may not be needed. Now http is processed (frontend) in clientside, so sessions are not as necessary. But they are still used for the admin site and other features.
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'learning.apps.LearningConfig',
    "debug_toolbar", # useful for viewing sequel queries through the 'view', requests and response
]
# The migrate command looks at the INSTALLED_APPS setting
# and creates any necessary database tables according to the database settings in your boilerplate/settings.py file
# and the database migrations shipped with the app.

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'boilerplate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boilerplate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_django_db',          # Your MySQL database name
        'USER': 'root',       # Your MySQL username
        'PASSWORD': 'pass',     # Your MySQL password
        'HOST': '127.0.0.1',             # Or 'localhost', or server IP
        'PORT': '3306',                  # Default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================================
# CHUNK 1: AUTHENTICATION BACKENDS
# ============================================================================
# Configure custom authentication backends for email-based and token-based auth.
# Django queries these in order; first match wins.
# Flow: authenticate() -> backend.authenticate() -> backend.get_user().

# CHOOSE YOUR HASHING LOGIC, IN ORDER OF PRECEDENCE
# STORED AS <algorithm>$<iterations>$<salt/seed>$<hash>
# OTHER LOGICS ENABLES, CHECKING OF PASSWORDS WITH THAT HASHING LOGIC, BUT NEW PASSWORDS WILL BE HASHED WITH THE FIRST LOGIC IN THE LIST.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/
AUTHENTICATION_BACKENDS = [
    # Allow login via email and password (instead of default username).
    'learning.auth_backends.SimpleEmailBackend',
    # Allow login via bearer token (API keys, JWT, etc.).
    'learning.auth_backends.TokenBackend',
    # Fall back to default username/password auth if custom backends fail.
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Third-party gateway settings (demo defaults; override via env vars).
THIRD_PARTY_BASE_URL = os.getenv("THIRD_PARTY_BASE_URL", "http://localhost:9000")
THIRD_PARTY_USER = os.getenv("THIRD_PARTY_USER", "demo")
THIRD_PARTY_PASSWORD = os.getenv("THIRD_PARTY_PASSWORD", "demo")
THIRD_PARTY_TIMEOUT_SECONDS = int(os.getenv("THIRD_PARTY_TIMEOUT_SECONDS", "3"))

# Idempotency cache windows (seconds) for transactional requests.
TRANSACTION_PENDING_TTL_SECONDS = int(os.getenv("TRANSACTION_PENDING_TTL_SECONDS", "300"))
TRANSACTION_COMPLETED_TTL_SECONDS = int(os.getenv("TRANSACTION_COMPLETED_TTL_SECONDS", "900"))
TRANSACTION_REVERSE_AFTER_SECONDS = int(os.getenv("TRANSACTION_REVERSE_AFTER_SECONDS", "600"))
